config/routes.rb
Raptor::Application.routes.draw do
  resources :experiments
  resources :variations
  resources :changes

  root :to => 'experiments#index'

  match 'admin', to: 'experiments#index', via: 'get'
  match 'js', to: 'index#index', via: 'get'

end

app/models/change.rb
class Change < ActiveRecord::Base
  belongs_to :variation

  validates_uniqueness_of :selector, scope: :variation_id

end

app/controllers/changes_controller.rb
class ChangesController < InheritedResources::Base

  before_action :authenticate
  skip_before_filter :verify_authenticity_token

  def permitted_params
    params.permit(:change => [:content, :selector, :css_text, :variation_id])
  end

  def create
    create!{
      unless @change.errors.any?
        back_to_experiment and return
      else
        render 'new' and return
      end
    }
  end

  def destroy
    destroy!{back_to_experiment and return}
  end

  private

  def back_to_experiment
    redirect_to @change.variation.experiment
  end

end

app/views/changes/_form.html.slim
= simple_form_for(@change) do |f|
  = f.error_notification

  .form-inputs
    div style='display:none'
      = f.association :variation
    div class='mt20'
      = f.input :selector
    div class='mt20'
      = f.input :content
    div class='mt20'
      = f.input :css_text

  br

  .form-actions
    = f.button :submit, class: "btn btn-warning"

app/views/changes/_index.html.slim
div class='ml20 mt20 fs12'
  -@experiment.variations.each do |variation|
    - variation.changes.each do |change|
      div class="change-of-variation change-of-variation-#{{variation.id}} mt10"
        div class='fr mr20 cp red'
          = link_to 'x' , change_path(change), method: :delete, class: 'red'
        b
          = change.selector
        - if change.content.size > 0
          div class='ml20 gray'
            span class='black' Content:&nbsp;
            = change.content
        - if change.css_text.size > 0
          div class='ml20 gray'
            span class='black' CSS Text:&nbsp;
            = change.css_text

app/views/changes/new.html.slim
h1 New change

== render 'form'