config/routes.rb
Raptor::Application.routes.draw do
  resources :experiments
  resources :variations
  resources :changes

  root :to => 'experiments#index'

  match 'admin', to: 'experiments#index', via: 'get'
  match 'js', to: 'index#index', via: 'get'

end

app/models/variation.rb
class Variation < ActiveRecord::Base
  belongs_to :experiment
  has_many :changes

  validate :valid_population_logic
  validates_presence_of :experiment, :title

  scope :not_zero, ->{where("population_logic != '100-100'")}

  def valid_population_logic

    return if population_logic == "100-100"

    ranges = Variation.get_ranges_for(experiment_id,id)

    populations = population_logic.split ","
    populations.each do |population|
      range = population.split "-"
      errors.add(:population_logic, "invalid range") unless range.size == 2
      errors.add(:population_logic, "Population test exceeds 100%") unless range[1].to_i < 100
      range.each do |r|
        errors.add(:population_logic, "invalid number") unless r.try(:to_i)
      end
      r = Range.new(range[0],range[1])
      ranges.each do |range|
        errors.add(:population_logic, "population already in use") unless (r.to_a & range.to_a).empty?
      end
    end
  end

  def self.get_ranges_for(experiment_id,id)
    ranges = []

    other_variations = Variation.where(experiment_id: experiment_id).not_zero
    other_variations = other_variations.where('id <> ?',id) if id
    other_variations.each do |variation|
      populations = variation.population_logic.split ","
      populations.each do |population|
        range = population.split "-"
        ranges << Range.new(range[0],range[1])
      end
    end

    ranges

  end

  def self.get_percentual(population_logic)
    return 0 unless population_logic
    return 0 if population_logic == "100-100"
    ranges = population_logic.split("-")
    "#{ranges[1].to_i - ranges[0].to_i + 1}"
  end

end

app/controllers/variations_controller.rb
class VariationsController < InheritedResources::Base
  before_action :authenticate
  before_action :reorganize, only: :update
  before_action :get_population_logic, only: [:create,:update]
  skip_before_filter :verify_authenticity_token

  def permitted_params
    params.permit(:variation => [:title, :population_logic, :experiment_id])
  end

  def create
    create!{
      unless @variation.errors.any?
        back_to_experiment and return
      else
        render 'new' and return
      end
    }
  end

  def update
    update!{back_to_experiment and return}
  end

  def destroy
    destroy!{back_to_experiment and return}
  end

  private

  def back_to_experiment
    redirect_to @variation.experiment || @experiment
  end

  def get_population_logic
    return unless params[:variation][:population_logic] and params[:variation][:experiment_id]
    return params[:variation][:population_logic] = population_logic
  end

  def population_logic
    return "100-100" if params[:variation][:population_logic] == "0"
    ranges = Variation.get_ranges_for(params[:variation][:experiment_id],params[:id])
    first_range = max_range(ranges) + 1
    "#{first_range}-#{first_range+params[:variation][:population_logic].to_i - 1}"
  end

  def max_range(ranges)
    (ranges.map(&:to_a).flatten - ["100"]).map(&:to_i).max || -1
  end

  def reorganize
    current_range = 0
    other_variations = Variation.where(experiment_id: params[:variation][:experiment_id]).where('id <> ?',params[:id]).not_zero.all
    other_variations.each do |variation|
      ranges = variation.population_logic.split("-")
      range_size = ranges[1].to_i - ranges[0].to_i
      variation.update(population_logic: "#{current_range}-#{current_range+range_size}")
      variation.save(validate: false)
      current_range = current_range + range_size + 1
    end
  end

end

app/views/variations/_form.html.slim
= simple_form_for(@variation) do |f|
  = f.error_notification

  .form-inputs
    div style='display:none'
      = f.association :experiment

    div class='cb'

    div class='mt20'
      = f.input :title

    = f.input :population_logic
    div id="population-slider" class="dragdealer" style='width:679px;'
      div class="handle red-bar"
        span class='value'
        | %

  br
  br

  .form-actions
    = f.button :submit, class: 'btn btn-warning'

  javascript:

    var d = new Dragdealer('population-slider', {
      animationCallback: function (x, y) {
        setup_fields(Math.round(x * 100));
      }
    });

    d.setValue(#{{(Variation.get_percentual @variation.population_logic).to_f/100}});

    function setup_fields(value) {
      $('#population-slider .value').text(value);
      $('#variation_population_logic').val(value);
    }

app/views/variations/_tabs.html.slim
- total_percent = 0
- @experiment.variations.each do |variation|
  - total_percent += Variation.get_percentual(variation.population_logic).to_i
  div class='fl ml50 mt20 fs12'
    div onclick='Raptor.Pages.Experiment.selectVariation(#{variation.id},#{total_percent})' class='cp tab-variation' id="tab-variation-#{variation.id}"
      = Variation.get_percentual variation.population_logic
      | % -&nbsp;
      = variation.title
    div
      = link_to 'Edit', edit_variation_path(variation), class: 'fl'
      = link_to 'Delete', variation_path(variation), method: :delete , class:'fl ml10'
      = link_to 'View', @experiment.url + "?forceversion=#{(total_percent-1)}&seedrafts=true", target: '_blank', class: 'ml10'
div class='fr fs12 mr20 mt20'
  = 100 - total_percent
  | % -&nbsp;
  | Control

app/views/variations/edit.html.slim
h1 Editing variation

== render 'form'

app/views/variations/new.html.slim
h1 New variation

== render 'form'