config/routes.rb
Raptor::Application.routes.draw do
  resources :experiments
  resources :variations
  resources :changes

  root :to => 'experiments#index'

  match 'admin', to: 'experiments#index', via: 'get'
  match 'js', to: 'index#index', via: 'get'

end

app/models/experiment.rb
class Experiment < ActiveRecord::Base

  has_many :variations

  STATUSES = ['draft', 'published']

  scope :visible, -> { where("status = 'published' or status = 'draft'") }

  validates_presence_of :title
  validates_presence_of :url
  validates_inclusion_of :status, in: STATUSES

  def published?
    published_until > Time.now
  end

  def css_class
    published? ? 'published' : 'draft'
  end

end

app/controllers/experiments_controller.rb
class ExperimentsController < InheritedResources::Base

  before_action :authenticate

  def permitted_params
    params.permit(:experiment => [:title, :status, :published_until, :country_code, :url])
  end

end

app/views/experiments/_form.html.slim
= simple_form_for @experiment do |f|
  = f.error_notification
  br
  br

  .field
    = f.input :title
  .field
    = f.input :url
  .field
    = f.label :status
    = f.select :status, ['draft','published']
  .field
    label Country
    = render 'snippets/countries_dropdown'
  .field
    = f.label :published_until
    = f.datetime_select :published_until, end_year: 2050

  input type='checkbox' class='fl' onclick='Raptor.Lib.Experiment.publishForever(this)'
  div class='fl ml10' Publish forever

  div class='cb'

  .actions = f.button :submit, class: 'btn btn-warning mt30'

app/views/experiments/edit.html.slim
h1 Editing experiment

== render 'form'

= link_to 'Show', @experiment

app/views/experiments/index.html.slim
h1 Experiments

table
  thead
    tr
      th Title
      th Status
      th Published until
      th Country
      th URL
      th
      th

  tbody
    - @experiments.each do |experiment|
      tr
        td class="table_title" = link_to experiment.title, experiment
        td class=experiment.status = experiment.status
        td class=experiment.css_class = experiment.published_until.strftime('%d/%m/%Y %H:%M')
        td
          == render 'snippets/country_flag', country_code: experiment.country_code
        td = link_to experiment.url, experiment.url
        td = link_to 'Edit', edit_experiment_path(experiment)
        td = link_to 'Delete', experiment_path(experiment), method: :delete

br


= link_to 'New Experiment', new_experiment_path, class: "btn btn-success ml20"

app/views/experiments/new.html.slim
h1 New experiment

== render 'form'

= link_to 'Back', experiments_path

app/views/experiments/show.html.slim
p#notice = notice
div class='fl' style='width:500px;'
  h1
    = @experiment.title
    - label_type = @experiment.status == "draft" ? "danger" : "success"
  p class="fl label label-#{{label_type}} mt3 fl"
    = @experiment.status
  p class='fl ml20'
    strong Published until:
    p class='fl ml20' = @experiment.published_until.strftime('%d/%m/%Y %H:%M')

  = link_to 'Edit', edit_experiment_path(@experiment), class: 'fl ml20'

  div class='cb'
    div class='fl mt10'
      | URL: &nbsp;
      = link_to @experiment.url, @experiment.url

  div class='cb'
    div class='mt10 fl'
      div class='fl'
        | Running on
      div class='fl ml10'
        == render 'snippets/country_flag', country_code: @experiment.country_code

  br
  br
div class='fr' style='min-width:630px'
  div class='mt30 fr mr20'
    = link_to 'New Variation', new_variation_path( variation: {experiment_id: @experiment.id}) , class: "btn btn-success ml20"

  div class='mt100'
    - if @experiment.variations.any?
      | Variations:
    div
      == render 'variations/tabs'



div class='cb'

table class='iframe-experiment'
  tr
    td width='85%'
      iframe src="#{{@experiment.url}}?forceversion=0" onload="Raptor.Pages.Experiment.checkJSPresence()"
    td valign='top'
      - if @experiment.variations.any?
        div class='ml20 mt10'
          | Changes
        == render 'changes/index'
        = link_to 'New Change', new_change_path( change: {variation_id: 0}) , class: 'btn btn-warning ml20 mt20', id: 'new-change'
br
br

javascript:
  var raptorLoaded = false;
  Raptor.Pages.Experiment.currentVariationId = #{{@experiment.variations.first.try(:id)}};
  Raptor.Pages.Experiment.initialize();